---
- name: Изменение имени машины на имя из Inventory
  hosts: all
  roles:
    - role: change_hostname
  tags:
    - change_hostname

- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

#- name: Установка и настройка проксирующего nginx
#  hosts: nginx # Будет работать на узлах в группе nginx
#  roles:
#    - role: nginx_proxy
#  tags:
#    - nginx_proxy

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_host
  tags:
    - nginx_host
